/**
 * Per-worktree local Supabase isolation.
 *
 * Linked git worktrees get their own Supabase project_id and port block so
 * `db:reset` in one worktree does not mutate another worktree's auth/users rows.
 * Main worktree (not a linked worktree) keeps the default supabase/config.toml.
 */

import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { rootLogger } from "../../src/lib/logging";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.join(__dirname, "..", "..");
const BASE_CONFIG = path.join(projectRoot, "supabase", "config.toml");
const WORKTREE_DIR = path.join(projectRoot, "supabase", ".worktree");
const WORKTREE_CONFIG = path.join(WORKTREE_DIR, "config.toml");
const WORKTREE_META = path.join(WORKTREE_DIR, "meta.json");

const BASE_PORTS = {
	api: 54321,
	db: 54322,
	studio: 54323,
	inbucket: 54324,
	smtp: 1025,
} as const;

const PORT_STEP = 10;

type WorktreePorts = {
	api: number;
	db: number;
	studio: number;
	inbucket: number;
	smtp: number;
};

type WorktreeMeta = {
	slug: string;
	projectId: string;
	ports: WorktreePorts;
};

function findMainWorktreeRoot(): string | null {
	let gitDir: string;
	let gitCommonDir: string;
	try {
		gitDir = execFileSync("git", ["rev-parse", "--git-dir"], {
			cwd: projectRoot,
			encoding: "utf8",
		}).trim();
		gitCommonDir = execFileSync("git", ["rev-parse", "--git-common-dir"], {
			cwd: projectRoot,
			encoding: "utf8",
		}).trim();
	} catch {
		return null;
	}

	const absoluteGitDir = path.resolve(projectRoot, gitDir);
	const absoluteCommonDir = path.resolve(projectRoot, gitCommonDir);
	if (absoluteGitDir === absoluteCommonDir) {
		return null;
	}
	return path.dirname(absoluteCommonDir);
}

function worktreeSlug(): string {
	const branch = execFileSync("git", ["branch", "--show-current"], {
		cwd: projectRoot,
		encoding: "utf8",
	}).trim();
	const normalized = branch
		.toLowerCase()
		.replaceAll(/[^a-z0-9]+/g, "-")
		.replaceAll(/^-+|-+$/g, "");
	return (normalized || "worktree").slice(0, 40);
}

function portSlot(slug: string): number {
	const digest = createHash("sha256").update(slug).digest();
	// Reserve slot 0 for the main worktree defaults; worktrees use slots 1-8.
	return ((digest.at(0) ?? 0) % 8) + 1;
}

function portsForSlug(slug: string): WorktreePorts {
	const slot = portSlot(slug);
	return {
		api: BASE_PORTS.api + slot * PORT_STEP,
		db: BASE_PORTS.db + slot * PORT_STEP,
		studio: BASE_PORTS.studio + slot * PORT_STEP,
		inbucket: BASE_PORTS.inbucket + slot * PORT_STEP,
		smtp: BASE_PORTS.smtp + slot,
	};
}

function upsertEnvLine(content: string, key: string, value: string): string {
	const line = `${key}=${value}`;
	const pattern = new RegExp(`^${key}=.*$`, "m");
	if (pattern.test(content)) {
		return content.replace(pattern, line);
	}
	return `${content.trimEnd()}\n${line}\n`;
}

function materializeEnvLocal(mainRoot: string, ports: WorktreePorts): void {
	const envPath = path.join(projectRoot, ".env.local");
	let content = "";

	try {
		if (fs.lstatSync(envPath).isSymbolicLink()) {
			const target = fs.readlinkSync(envPath);
			const resolved = path.resolve(path.dirname(envPath), target);
			content = fs.readFileSync(resolved, "utf8");
			fs.unlinkSync(envPath);
		} else if (fs.existsSync(envPath)) {
			content = fs.readFileSync(envPath, "utf8");
		} else {
			const mainEnv = path.join(mainRoot, ".env.local");
			if (fs.existsSync(mainEnv)) {
				content = fs.readFileSync(mainEnv, "utf8");
			}
		}
	} catch {
		const mainEnv = path.join(mainRoot, ".env.local");
		if (fs.existsSync(mainEnv)) {
			content = fs.readFileSync(mainEnv, "utf8");
		}
	}

	content = upsertEnvLine(content, "SUPABASE_URL", `http://127.0.0.1:${ports.api}`);
	content = upsertEnvLine(
		content,
		"DATABASE_URL",
		`postgresql://postgres:postgres@127.0.0.1:${ports.db}/postgres`,
	);
	content = upsertEnvLine(content, "EMAIL_SMTP_PORT", String(ports.smtp));

	fs.writeFileSync(envPath, content, "utf8");
}

function writeWorktreeConfig(meta: WorktreeMeta): void {
	const base = fs.readFileSync(BASE_CONFIG, "utf8");
	const overrides = `
# --- worktree isolation (generated by scripts/db/worktree-supabase.ts) ---
project_id = "${meta.projectId}"

[api]
port = ${meta.ports.api}

[db]
port = ${meta.ports.db}

[studio]
port = ${meta.ports.studio}

[inbucket]
port = ${meta.ports.inbucket}
smtp_port = ${meta.ports.smtp}
`;

	fs.mkdirSync(WORKTREE_DIR, { recursive: true });
	fs.writeFileSync(WORKTREE_CONFIG, `${base.trimEnd()}\n${overrides}`, "utf8");
	fs.writeFileSync(WORKTREE_META, `${JSON.stringify(meta, null, 2)}\n`, "utf8");
}

export function ensureWorktreeSupabaseConfig(): WorktreeMeta | null {
	const mainRoot = findMainWorktreeRoot();
	if (!mainRoot) {
		return null;
	}

	const slug = worktreeSlug();
	const ports = portsForSlug(slug);
	const meta: WorktreeMeta = {
		slug,
		projectId: `stocktextalerts-wt-${slug}`,
		ports,
	};

	writeWorktreeConfig(meta);
	materializeEnvLocal(mainRoot, ports);

	rootLogger.info("worktree-supabase — configured isolated local stack", {
		action: "worktree_supabase_setup",
		slug: meta.slug,
		projectId: meta.projectId,
		ports: meta.ports,
		config: WORKTREE_CONFIG,
	});

	return meta;
}

function main(): void {
	ensureWorktreeSupabaseConfig();
}

const invokedDirectly =
	process.argv[1] !== undefined &&
	pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url;

if (invokedDirectly) {
	main();
}
