#!/usr/bin/env tsx
/**
 * Writes src/lib/logging/release-id.ts with the current git commit SHA.
 * Called by the `prebuild` npm hook (Vercel/Astro) and by aws/deploy-web.sh
 * before `sam build`. The resulting file is committed as a stub ("dev") and
 * overwritten here at build time; never commit the overwritten version.
 *
 * SHA resolution order:
 *   1. VERCEL_GIT_COMMIT_SHA (set automatically on Vercel build infra)
 *   2. GITHUB_SHA (GitHub Actions)
 *   3. git rev-parse HEAD (works locally and in the Lambda deploy script)
 *   4. "dev" (fallback — no git or env var available)
 *
 * Dirty detection uses `git status --porcelain -uno` (tracked files only) to
 * avoid false positives from gitignored files like .env.local.
 */
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

function run(cmd: string): string {
	try {
		return execSync(cmd, { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
	} catch {
		return "";
	}
}

const repoRoot = resolve(import.meta.dirname, "..");

const fromEnv =
	process.env.VERCEL_GIT_COMMIT_SHA ?? process.env.GITHUB_SHA ?? "";
let sha = fromEnv || run("git rev-parse HEAD");

let releaseId = sha ? sha.slice(0, 12) : "dev";

// Skip dirty detection on Vercel/CI (always a clean checkout from a fixed commit ref)
// and when SHA came from env var (canonical, not from working-tree state).
if (sha && !fromEnv) {
	const dirty = run("git status --porcelain -uno");
	if (dirty) {
		releaseId += "-dirty";
	}
}

const outPath = resolve(repoRoot, "src/lib/logging/release-id.ts");
const content = `// Generated by scripts/gen-release-id.ts — do not commit this version.
export const RELEASE_ID = ${JSON.stringify(releaseId)};
`;
writeFileSync(outPath, content);
process.stdout.write(`release-id: ${releaseId}\n`);
