import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { rootLogger } from "../src/lib/logging";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.join(__dirname, "..");

const OUTPUT_PATH = path.join(
  projectRoot,
  "src",
  "lib",
  "db",
  "generated",
  "database.types.ts",
);

function getProjectRef(url: string): string {
  const host = new URL(url).hostname;
  const ref = host.split(".")[0];
  if (!ref) {
    throw new Error(`Unable to derive Supabase project ref from ${url}`);
  }
  return ref;
}

function buildHeader(): string {
  return `/*
 * This file is auto-generated by \`npm run db:gen-types:prod\`
 * Do not edit manually - your changes will be overwritten
 *
 * To regenerate: npm run db:gen-types:prod
 */
`;
}

function main(): void {
  const supabaseUrl = process.env.PUBLIC_SUPABASE_URL as string;

  const projectRef = getProjectRef(supabaseUrl);
  const types = execFileSync(
    "supabase",
    ["gen", "types", "typescript", "--project-id", projectRef, "--schema", "public"],
    { encoding: "utf-8" },
  );

  fs.writeFileSync(OUTPUT_PATH, `${buildHeader()}${types}`);

  rootLogger.info("Generated production database types.", {
    context: { outputPath: OUTPUT_PATH, projectRef },
  });
}

try {
  main();
} catch (error) {
  rootLogger.error(
    "Generate production types failed.",
    { context: { outputPath: OUTPUT_PATH } },
    error instanceof Error ? error : new Error(String(error)),
  );
  process.exit(1);
}
