-- Add missing asset_events table, asset_event_type enum, and insider/scheduling
-- columns on users that were referenced in code but never created in migrations.

/* ================================================================
   1. ENUM — asset_event_type
   ================================================================ */

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'asset_event_type') THEN
    CREATE TYPE public.asset_event_type AS ENUM ('earnings', 'dividend', 'split');
  END IF;
END $$;

/* ================================================================
   2. TABLE — asset_events
   ================================================================ */

CREATE TABLE IF NOT EXISTS public.asset_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol VARCHAR(10) NOT NULL REFERENCES public.assets(symbol) ON DELETE CASCADE,
  event_type public.asset_event_type NOT NULL,
  event_date DATE NOT NULL,
  week_of DATE NOT NULL,
  data JSONB DEFAULT '{}'::jsonb NOT NULL,
  fetched_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS asset_events_symbol_type_date_idx
  ON public.asset_events (symbol, event_type, event_date);

CREATE INDEX IF NOT EXISTS idx_asset_events_week_of
  ON public.asset_events (week_of);

ALTER TABLE public.asset_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.asset_events FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.asset_events TO service_role;

/* ================================================================
   3. COLUMNS — users: insider toggles + scheduling
   ================================================================ */

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS asset_events_include_insider_email BOOLEAN DEFAULT false NOT NULL,
  ADD COLUMN IF NOT EXISTS asset_events_include_insider_sms   BOOLEAN DEFAULT false NOT NULL,
  ADD COLUMN IF NOT EXISTS asset_events_next_send_at          TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS asset_events_last_analyst_sent_month TEXT;

CREATE INDEX IF NOT EXISTS idx_users_asset_events_next_send_at
  ON public.users (asset_events_next_send_at)
  WHERE asset_events_next_send_at IS NOT NULL;
