-- Extract IPO events from asset_events into a new market_events table.
-- market_events has no FK to assets, so IPO tickers that don't exist in assets
-- won't cause FK violations.

-- 1. Create market_events table
CREATE TABLE IF NOT EXISTS public.market_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type VARCHAR(20) NOT NULL,
  symbol VARCHAR(10) NOT NULL,
  event_date DATE NOT NULL,
  week_of DATE NOT NULL,
  data JSONB DEFAULT '{}'::jsonb NOT NULL,
  fetched_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_market_events_type_symbol_date
  ON public.market_events (event_type, symbol, event_date) NULLS NOT DISTINCT;

CREATE INDEX IF NOT EXISTS idx_market_events_type_date
  ON public.market_events (event_type, event_date);

ALTER TABLE public.market_events ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.market_events TO service_role;

-- 2. Migrate existing IPO rows
INSERT INTO public.market_events (event_type, symbol, event_date, week_of, data)
SELECT 'ipo', symbol, event_date, week_of, data
FROM public.asset_events
WHERE event_type = 'ipo'
ON CONFLICT (event_type, symbol, event_date) DO NOTHING;

-- 3. Delete IPO rows from asset_events
DELETE FROM public.asset_events WHERE event_type = 'ipo';

-- 4. Drop scope column and related objects
DROP INDEX IF EXISTS idx_asset_events_scope_event_date;
ALTER TABLE public.asset_events DROP COLUMN IF EXISTS scope;
DROP TYPE IF EXISTS public.asset_event_scope;

-- 5. Remove 'ipo' from asset_event_type enum (rename-recreate-drop pattern)
ALTER TYPE public.asset_event_type RENAME TO asset_event_type_old;

CREATE TYPE public.asset_event_type AS ENUM ('earnings', 'dividend', 'split');

ALTER TABLE public.asset_events
  ALTER COLUMN event_type TYPE public.asset_event_type
  USING event_type::text::public.asset_event_type;

DROP TYPE public.asset_event_type_old;

-- 6. Update schema version
UPDATE public.app_metadata
  SET value = '20260306160000_market_events'
  WHERE key = 'schema_version';
