-- Short interest daily Asset Events facet: store + notification_options.

SET lock_timeout = '5s';
SET statement_timeout = '30s';

INSERT INTO public.notification_options (notification_type, content, channel) VALUES
  ('daily_notification', 'short_interest', 'email'),
  ('daily_notification', 'short_interest', 'telegram');

CREATE TABLE public.asset_short_interest (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  symbol text NOT NULL,
  settlement_date date NOT NULL,
  short_interest bigint NOT NULL,
  avg_daily_volume bigint,
  days_to_cover numeric,
  share_class_shares_outstanding bigint,
  fetched_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT asset_short_interest_pkey PRIMARY KEY (id),
  CONSTRAINT asset_short_interest_symbol_settlement_key UNIQUE (symbol, settlement_date),
  CONSTRAINT asset_short_interest_symbol_fkey FOREIGN KEY (symbol)
    REFERENCES public.assets(symbol) ON DELETE CASCADE,
  CONSTRAINT asset_short_interest_short_interest_nonneg CHECK (short_interest >= 0),
  CONSTRAINT asset_short_interest_avg_daily_volume_nonneg CHECK (
    avg_daily_volume IS NULL OR avg_daily_volume >= 0
  ),
  CONSTRAINT asset_short_interest_days_to_cover_nonneg CHECK (
    days_to_cover IS NULL OR days_to_cover >= 0
  ),
  CONSTRAINT asset_short_interest_shares_outstanding_positive CHECK (
    share_class_shares_outstanding IS NULL OR share_class_shares_outstanding > 0
  )
);

CREATE INDEX idx_asset_short_interest_settlement_date
  ON public.asset_short_interest (settlement_date DESC);

CREATE INDEX idx_asset_short_interest_symbol_settlement
  ON public.asset_short_interest (symbol, settlement_date DESC);

ALTER TABLE public.asset_short_interest OWNER TO postgres;
ALTER TABLE public.asset_short_interest ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.asset_short_interest TO service_role;
GRANT ALL ON SEQUENCE public.asset_short_interest_id_seq TO service_role;

UPDATE public.app_metadata
SET value = '20260803132442_short_interest_digest_facet'
WHERE key = 'schema_version';
