-- squawk-ignore-file constraint-missing-not-valid
-- SEC filings daily Asset Events facet: CIK on assets, filings store, notification_options.
-- (Supabase applies each migration in ONE transaction, so NOT VALID + VALIDATE
-- in the same file is the only option; squawk still wants them split.)

SET lock_timeout = '5s';
SET statement_timeout = '30s';

INSERT INTO public.notification_options (notification_type, content, channel) VALUES
  ('daily_notification', 'filings', 'email'),
  ('daily_notification', 'filings', 'telegram');

ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS cik text;

COMMENT ON COLUMN public.assets.cik IS
  'SEC Central Index Key, 10-digit zero-padded. Nullable when unmapped; not unique (share classes share a CIK).';

ALTER TABLE public.assets
  ADD CONSTRAINT assets_cik_format
  CHECK (cik IS NULL OR cik ~ '^[0-9]{10}$') NOT VALID;

ALTER TABLE public.assets VALIDATE CONSTRAINT assets_cik_format;

CREATE INDEX IF NOT EXISTS idx_assets_cik
  ON public.assets (cik)
  WHERE cik IS NOT NULL;

CREATE TABLE public.asset_sec_filings (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  symbol text NOT NULL,
  cik text NOT NULL,
  accession_number text NOT NULL,
  form text NOT NULL,
  filed_at timestamp with time zone NOT NULL,
  primary_document text,
  fetched_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT asset_sec_filings_pkey PRIMARY KEY (id),
  CONSTRAINT asset_sec_filings_symbol_accession_key UNIQUE (symbol, accession_number),
  CONSTRAINT asset_sec_filings_symbol_fkey FOREIGN KEY (symbol)
    REFERENCES public.assets(symbol) ON DELETE CASCADE,
  CONSTRAINT asset_sec_filings_cik_format CHECK (cik ~ '^[0-9]{10}$'),
  CONSTRAINT asset_sec_filings_accession_no_whitespace CHECK (public.has_no_whitespace(accession_number)),
  CONSTRAINT asset_sec_filings_form_no_whitespace CHECK (public.has_no_whitespace(form))
);

CREATE INDEX idx_asset_sec_filings_symbol_filed_at
  ON public.asset_sec_filings (symbol, filed_at DESC);

CREATE INDEX idx_asset_sec_filings_filed_at
  ON public.asset_sec_filings (filed_at);

ALTER TABLE public.asset_sec_filings OWNER TO postgres;
ALTER TABLE public.asset_sec_filings ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.asset_sec_filings TO service_role;
GRANT ALL ON SEQUENCE public.asset_sec_filings_id_seq TO service_role;

UPDATE public.app_metadata
SET value = '20260725114053_sec_filings_digest_facet'
WHERE key = 'schema_version';
