-- Persist Finnhub analyst consensus and insider transactions for send-time DB reads.

SET lock_timeout = '5s';
SET statement_timeout = '30s';

CREATE TABLE public.asset_analyst_consensus (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  symbol text NOT NULL,
  period text,
  buy integer,
  hold integer,
  sell integer,
  strong_buy integer,
  strong_sell integer,
  fetch_succeeded boolean DEFAULT false NOT NULL,
  fetched_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT asset_analyst_consensus_pkey PRIMARY KEY (id),
  CONSTRAINT asset_analyst_consensus_symbol_key UNIQUE (symbol),
  CONSTRAINT asset_analyst_consensus_symbol_fkey FOREIGN KEY (symbol)
    REFERENCES public.assets(symbol) ON DELETE CASCADE
);

CREATE INDEX idx_asset_analyst_consensus_symbol_fetched_at
  ON public.asset_analyst_consensus (symbol, fetched_at DESC);

CREATE TABLE public.asset_insider_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  symbol text NOT NULL,
  transaction_date date NOT NULL,
  name text NOT NULL,
  share numeric NOT NULL,
  change numeric NOT NULL,
  transaction_type text DEFAULT ''::text NOT NULL,
  fetched_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT asset_insider_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT asset_insider_transactions_symbol_date_name_change_key
    UNIQUE (symbol, transaction_date, name, change),
  CONSTRAINT asset_insider_transactions_symbol_fkey FOREIGN KEY (symbol)
    REFERENCES public.assets(symbol) ON DELETE CASCADE
);

CREATE INDEX idx_asset_insider_transactions_symbol_date
  ON public.asset_insider_transactions (symbol, transaction_date DESC);

ALTER TABLE public.asset_analyst_consensus ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asset_insider_transactions ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.asset_analyst_consensus TO service_role;
GRANT ALL ON SEQUENCE public.asset_analyst_consensus_id_seq TO service_role;
GRANT ALL ON TABLE public.asset_insider_transactions TO service_role;
GRANT ALL ON SEQUENCE public.asset_insider_transactions_id_seq TO service_role;

UPDATE public.app_metadata
SET value = '20260601191106_persist_finnhub_asset_enrichment'
WHERE key = 'schema_version';
